version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - 32000:3306
  
  angular:
    image: natyarteagac/books-angular:v1
    ports:
      - 4200:4200

  flask:
    image: natyarteagac/books-flask-api:v1
    environment:
      MYSQL_USER: root
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - 5000:5000
    depends_on:
      - mysql
    restart:
      on-failure
